org.jellyfin.sdk.model.api.**
org.jellyfin.sdk.model.api.*
org.jellyfin.sdk.model.**
org.jellyfin.sdk.model.api.BaseItemDto
org.jellyfin.sdk.model.api.BaseItemKind
org.jellyfin.sdk.model.api.BaseItemPerson
org.jellyfin.sdk.model.api.ChapterInfoDto
org.jellyfin.sdk.model.api.MediaSourceInfo
org.jellyfin.sdk.model.api.MediaStream
org.jellyfin.sdk.model.api.RecommendationDto
org.jellyfin.sdk.model.api.SeriesTimerInfoDto
org.jellyfin.sdk.model.api.SessionInfoDto
org.jellyfin.sdk.model.api.TimerInfoDto
org.jellyfin.sdk.model.api.UserDto
org.jellyfin.sdk.model.api.UserItemDataDto
